#### Pandas-DataFrame And Series
Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [2]:
import pandas as pd

In [4]:
# Series
##A Pandas Series is a one-dimensional array-like object that can hold any data type. It is similar to a column in a table

import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print("Series \n",series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [5]:
# Create a series from dictioary elemnts
data= {'a':1,'b':2,'c':3}
series_dictionary=pd.Series(data)
print(series_dictionary)

a    1
b    2
c    3
dtype: int64

In [6]:
data=[10,20,30,]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [25]:
# dataFrame
# create a datarame from a dictionary of unit

data={
'Name':['Om','Ram','Dhruv'],
'Age':[19,20,19],
'City':['Jabalpur','Indore','Bhopal']

}
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age      City
0     Om   19  Jabalpur
1    Ram   20    Indore
2  Dhruv   19    Bhopal
<class 'pandas.core.frame.DataFrame'>

In [10]:
import numpy as np
np.array(df)

array([['Om', 19, 'Jabalpur'],
       ['Ram', 20, 'Indore'],
       ['Dhruv', 19, 'Bhopal']], dtype=object)

In [ ]:
# Create a dataframe from list of dictionary

data=[
 { 'Name':'Om','Age':19,'City':'Jabalpur'},
 { 'Name':'Dhruv','Age':18,'City':'Bhopal'},
 { 'Name':'Hittu','Age':19,'City':'Indore'},
 { 'Name':'Ram','Age':17,'City':'Sihora'}
]
df = pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age      City
0     Om   19  Jabalpur
1  Dhruv   18    Bhopal
2  Hittu   19    Indore
3    Ram   17    Sihora
<class 'pandas.core.frame.DataFrame'>

In [16]:
df=pd.read_csv('sales_data.csv')
df.head(5)
# print(df.head)

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card

In [17]:
df.tail(5)

     Order ID  Amount  Profit  Quantity     Category Sub-Category PaymentMode
1495  B-25700       7      -3         2     Clothing  Hankerchief         COD
1496  B-25757    3151     -35         7     Clothing     Trousers         EMI
1497  B-25973    4141    1698        13  Electronics     Printers         COD
1498  B-25698       7      -2         1     Clothing  Hankerchief         COD
1499  B-25993    4363     305         5    Furniture       Tables         EMI

In [27]:
# Accessing data from dataframe

df

    Name  Age      City
0     Om   19  Jabalpur
1    Ram   20    Indore
2  Dhruv   19    Bhopal

In [30]:
df['Name']

0       Om
1      Ram
2    Dhruv
Name: Name, dtype: object

In [ ]:
df.loc[0]  #means picking up 0th index

Name          Om
Age           19
City    Jabalpur
Name: 0, dtype: object

In [37]:
df.iloc[0][2] #picking up by index

C:\Users\omdha\AppData\Local\Temp\ipykernel_4276\3027760209.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][2] #picking up by index

'Jabalpur'

In [ ]:
# Accessing a specified location

df.at[2,'Age']

np.int64(20)

In [41]:
df.at[2,'Name']

'Dhruv'

In [42]:
# Accessing a specified elemnt using iat

df.iat[2,2]

'Bhopal'

In [43]:
df

    Name  Age      City
0     Om   19  Jabalpur
1    Ram   20    Indore
2  Dhruv   19    Bhopal

In [47]:
# data manipulation with dataframes

df

    Name  Age      City  Salary
0     Om   19  Jabalpur   50000
1    Ram   20    Indore   60000
2  Dhruv   19    Bhopal   70000

add new columns 👇🏻

In [46]:
df['Salary']=[50000,60000,70000]
df

    Name  Age      City  Salary
0     Om   19  Jabalpur   50000
1    Ram   20    Indore   60000
2  Dhruv   19    Bhopal   70000

In [ ]:
# remove a column
df.drop('Salary',axis=1) 
# df.drop('Salary',axis=1,inplace=True)    #inplace-> removes permanently

In [55]:
df

    Name  Age      City
0     Om   19  Jabalpur
1    Ram   20    Indore
2  Dhruv   19    Bhopal

In [57]:
#ADD age to the column

df['Age']=df['Age']+1
df

    Name  Age      City
0     Om   21  Jabalpur
1    Ram   22    Indore
2  Dhruv   21    Bhopal

In [58]:
df.drop(0)

    Name  Age    City
1    Ram   22  Indore
2  Dhruv   21  Bhopal

In [59]:
df=pd.read_csv('sales_data.csv')
df.head(5)

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card

In [60]:
df.describe()

            Amount      Profit     Quantity
count  1500.000000  1500.00000  1500.000000
mean    291.847333    24.64200     3.743333
std     461.924620   168.55881     2.184942
min       4.000000 -1981.00000     1.000000
25%      47.750000   -12.00000     2.000000
50%     122.000000     8.00000     3.000000
75%     326.250000    38.00000     5.000000
max    5729.000000  1864.00000    14.000000