Data Manipulation and analysis with pandas

Definition of Data Manipulation & Analysis in Pandas

Data Manipulation and Analysis with Pandas means:

Using the Pandas library in Python to clean, organize, transform, and analyze data in order to extract useful information and insights.

🔍 In Simple Words

👉 It is the process of:

Manipulation = modifying data (cleaning, filtering, sorting, adding columns)
Analysis = understanding data (finding patterns, averages, trends)

In [3]:
import pandas as pd

In [22]:
df=pd.read_csv('orders.csv')
# fatch first 5 rows
df.head(5)

  Order ID  Order Date CustomerName           State     City
0  B-26055  10-03-2018    Harivansh   Uttar Pradesh  Mathura
1  B-25993  03-02-2018       Madhav           Delhi    Delhi
2  B-25973  24-01-2018  Madan Mohan   Uttar Pradesh  Mathura
3  B-25923  27-12-2018        Gopal     Maharashtra   Mumbai
4  B-25757  21-08-2018     Vishakha  Madhya Pradesh   Indore

In [5]:
df.tail(5)

    Order ID  Order Date CustomerName             State     City
495  B-25742  03-08-2018       Ashwin               Goa      Goa
496  B-26088  26-03-2018       Bhavna            Sikkim  Gangtok
497  B-25707  01-07-2018      Shivani       Maharashtra   Mumbai
498  B-25758  22-08-2018      Shubham  Himachal Pradesh    Simla
499  B-26095  28-03-2018      Monisha         Rajasthan   Jaipur

In [7]:
df.describe()

       Order ID  Order Date CustomerName        State    City
count       500         500          500          500     500
unique      500         307          336           19      25
top     B-26055  24-11-2018       Shreya  Maharashtra  Indore
freq          1           7            6           94      71

In [8]:
df.dtypes

Order ID        object
Order Date      object
CustomerName    object
State           object
City            object
dtype: object

In [ ]:
# handling missing values
# df.isnull().any()

Order ID        False
Order Date      False
CustomerName    False
State           False
City            False
dtype: bool

In [ ]:
# df.isnull().sum()

Order ID        0
Order Date      0
CustomerName    0
State           0
City            0
dtype: int64

In [23]:
df.fillna(0)

    Order ID  Order Date CustomerName             State     City
0    B-26055  10-03-2018    Harivansh     Uttar Pradesh  Mathura
1    B-25993  03-02-2018       Madhav             Delhi    Delhi
2    B-25973  24-01-2018  Madan Mohan     Uttar Pradesh  Mathura
3    B-25923  27-12-2018        Gopal       Maharashtra   Mumbai
4    B-25757  21-08-2018     Vishakha    Madhya Pradesh   Indore
..       ...         ...          ...               ...      ...
495  B-25742  03-08-2018       Ashwin               Goa      Goa
496  B-26088  26-03-2018       Bhavna            Sikkim  Gangtok
497  B-25707  01-07-2018      Shivani       Maharashtra   Mumbai
498  B-25758  22-08-2018      Shubham  Himachal Pradesh    Simla
499  B-26095  28-03-2018      Monisha         Rajasthan   Jaipur

[500 rows x 5 columns]

In [18]:
df.dtypes

Order ID        bool
Order Date      bool
CustomerName    bool
State           bool
City            bool
dtype: object

In [24]:
# Rename columms
df = df.rename(columns={'Date': 'Order Date'})
df.head()

  Order ID  Order Date CustomerName           State     City
0  B-26055  10-03-2018    Harivansh   Uttar Pradesh  Mathura
1  B-25993  03-02-2018       Madhav           Delhi    Delhi
2  B-25973  24-01-2018  Madan Mohan   Uttar Pradesh  Mathura
3  B-25923  27-12-2018        Gopal     Maharashtra   Mumbai
4  B-25757  21-08-2018     Vishakha  Madhya Pradesh   Indore

In [ ]:
# Change the datatypes

dff['Values']