Data Manipulation and analysis with pandas

Definition of Data Manipulation & Analysis in Pandas

Data Manipulation and Analysis with Pandas means:

Using the Pandas library in Python to clean, organize, transform, and analyze data in order to extract useful information and insights.

🔍 In Simple Words

👉 It is the process of:

Manipulation = modifying data (cleaning, filtering, sorting, adding columns)
Analysis = understanding data (finding patterns, averages, trends)

In [72]:
import pandas as pd

In [73]:
df=pd.read_csv('emplly.csv')
# fatch first 5 rows
df.head(5)

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069

In [74]:
df.tail(5)

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
249995,Software Engineer,17,PhD,2,Telecom,Enterprise,India,No,1,127791
249996,Frontend Developer,20,PhD,7,Telecom,Startup,Remote,No,2,154593
249997,Business Analyst,1,Bachelor,12,Retail,Enterprise,India,Yes,0,75988
249998,Data Scientist,0,High School,2,Consulting,Small,Sweden,Hybrid,5,90467
249999,Data Analyst,16,Diploma,2,Technology,Medium,UK,No,5,133084

In [75]:
df.describe()

       experience_years   skills_count  certifications         salary
count     250000.000000  250000.000000   250000.000000  250000.000000
mean          10.005408       9.997812        2.491928  145718.080524
std            6.060602       5.479288        1.706475   37407.952729
min            0.000000       1.000000        0.000000   31867.000000
25%            5.000000       5.000000        1.000000  119358.000000
50%           10.000000      10.000000        2.000000  143453.000000
75%           15.000000      15.000000        4.000000  169492.000000
max           20.000000      19.000000        5.000000  333046.000000

In [76]:
df.dtypes

job_title           object
experience_years     int64
education_level     object
skills_count         int64
industry            object
company_size        object
location            object
remote_work         object
certifications       int64
salary               int64
dtype: object

In [77]:
# handling missing values
# df.isnull().any()

In [78]:
# df.isnull().sum()

In [79]:
df.fillna(0)

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069
...,...,...,...,...,...,...,...,...,...,...
249995,Software Engineer,17,PhD,2,Telecom,Enterprise,India,No,1,127791
249996,Frontend Developer,20,PhD,7,Telecom,Startup,Remote,No,2,154593
249997,Business Analyst,1,Bachelor,12,Retail,Enterprise,India,Yes,0,75988
249998,Data Scientist,0,High School,2,Consulting,Small,Sweden,Hybrid,5,90467
249999,Data Analyst,16,Diploma,2,Technology,Medium,UK,No,5,133084

In [80]:
df.dtypes

job_title           object
experience_years     int64
education_level     object
skills_count         int64
industry            object
company_size        object
location            object
remote_work         object
certifications       int64
salary               int64
dtype: object

In [81]:
# Rename columms
df = df.rename(columns={'Date': 'Order Date'})
df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069

In [82]:
# Change Data types

df['skills_count_new']=df['skills_count'].fillna(df['skills_count'].mean()).astype(int)
df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary,skills_count_new
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413,2
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764,17
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123,4
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123,13
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069,7

In [83]:
df["skills_count_new"] = df["skills_count"].apply(lambda x: x * 2)
df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary,skills_count_new
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413,4
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764,34
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123,8
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123,26
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069,14

In [84]:
# Data Aggregating and grouping

df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary,skills_count_new
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413,4
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764,34
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123,8
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123,26
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069,14

In [88]:
grouped_mean=df.groupby('industry')['skills_count'].mean()
print(grouped_mean)

industry
Consulting        9.995645
Education         9.991080
Finance           9.974993
Government        9.984258
Healthcare       10.001687
Manufacturing     9.990649
Media            10.030998
Retail            9.954269
Technology       10.012970
Telecom          10.041876
Name: skills_count, dtype: float64